print("Ship Control Protocol v 2.1")
print("Installing: 0%")
shell.run("rm scp_functions.lua")
shell.run("wget https://raw.githubusercontent.com/MCNaOtlichnoYT/ShipControlProtocol/refs/heads/main/scp_functions.lua scp_functions.lua")
print("Installing: 33%")
shell.run("rm scp_config.lua")
shell.run("wget https://raw.githubusercontent.com/MCNaOtlichnoYT/ShipControlProtocol/refs/heads/main/scp_config.lua scp_config.lua")
print("Installing: 67%")
shell.run("rm panel.lua")
shell.run("wget https://raw.githubusercontent.com/MCNaOtlichnoYT/ShipControlProtocol/refs/heads/main/panel.lua panel.lua")
print("Installing: 100%")
